FROM node:16-buster
# ENV workdir=/app
# RUN useradd -m nodejs && \
#     mkdir -p $workdir && \
#     chown nodejs -R $workdir
# USER nodejs
# WORKDIR $workdir
#COPY --chown=nodejs backend/package.json backend/yarn.lock backend/tsconfig.json $workdir
#RUN yarn install
# COPY --chown=nodejs . /app
#RUN yarn build
#CMD ["yarn", "start"]